granite-13b:
  prompt_template: "granite-13b-sft-flan300k/prompt.txt"
  fn_completions: "huggingface_local_completions"
  completions_kwargs:
    model_name: "/new_data/rl-4-llm/granite_models/instruction_tuned/granite-13b-sft-flan300k/ckpt-500bn-base" # local path
    model_kwargs:
      torch_dtype: 'bfloat16'
    max_new_tokens: 2048
    temperature: 0.7
    top_p: 1.0
    do_sample: True
  pretty_name: "Flan 300k"
  # link: "https://huggingface.co/lmsys/vicuna-7b-delta-v1.1"